
product_name:"Iphone 15",
price: 829.99,
description:"iPhone 15 brings you Dynamic Island, a 48MP Main camera, and USB-C—all in a durable color-infused glass and aluminum design. ",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6417/6417993_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Iphone 14",
price: 629.99,
description:"With the most impressive dual-camera system on iPhone. Capture stunning photos in low light and bright light. Get peace of mind with groundbreaking safety features. ",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6504/6504794_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Iphone 13",
price: 579.99,
description:" The most advanced dual-camera system ever on iPhone. Lightning-fast A15 Bionic chip. A big leap in battery life. Durable design. ",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6417/6417788_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Iphone 12",
price: 554.99,
description:" 5G to download movies on the fly and stream high-quality video.¹ Beautifully bright 6.1-inch Super Retina XDR display.",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6417/6417831_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Samsung Galaxy s23",
price: 1199.99,
description:"S Series has a legacy of pushing the boundaries of what a smartphone can do. ",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6529/6529723_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Samsung Galaxy s22",
price: 699.99,
description:"Galaxy S22 is redefining the epic standard – both for what a smartphone can do with video and for what you can communicate, create, and experience with it",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6494/6494417_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Samsung Galaxy s21",
price: 399.99,
description:"Samsung Galaxy S21 FE 5G is jam-packed with features that help you get more out of whatever you're into",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6465/6465024cv18d.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Galaxy Note 20",
price: 499.99,
description:"Galaxy Note20 Ultra 5G connect you to everything you love at unprecedented speeds. ",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6533/6533176_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Samsung Galaxy s23 Ultra",
price: 1379.99,
description:"Galaxy S23 Ultra is more than the next big step in mobile tech. ",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6529/6529724_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Iphone 15 Pro Max",
price: 1099.99,
description:"iPhone 15 Pro Max. Forged in titanium and featuring the groundbreaking A17 Pro chip, a customizable Action button, and the most powerful iPhone camera system ever. ",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6525/6525424_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 1,

product_name:"Macbook Pro 14",
price: 1999.99,
description:"The 14-inch MacBook Pro with M2 Pro and M2 Max takes power and speed to the next level",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6455/6455369_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 2,

product_name:"Macbook Pro 13",
price: 1099.99,
description:"The 13-inch MacBook Pro is more capable than ever. Supercharged by the next-generation M2 chip, it’s Apple’s most portable pro laptop, with up to 20 hours of battery life.",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509652_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 2,

product_name:"Dell 13th Gen Laptop",
price: 729.99,
description:"Turn your content into immersive experiences with enhanced audio features and versatile modes on the new Inspiron 14 2-in-1 laptop. ",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6539/6539904_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 2,

product_name:"Macbook Air 15",
price: 1699.00,
description:"The 15-inch MacBook Air is impossibly thin and has a stunning Liquid Retina display.",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6552/6552867_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 2,

product_name:"Macbook Air 13.6",
price: 899.00,
description:"Supercharged by the next-generation M2 chip, the redesigned MacBook Air combines incredible performance and up to 18 hours of battery life into its strikingly thin aluminum enclosure.",
image:"https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6509/6509648_sd.jpg;maxHeight=640;maxWidth=550",
category_id: 2,

product_name:"",
price: ,
description:"",
image:"",
category_id: 2,

product_name:"",
price: ,
description:"",
image:"",
category_id: 2,

product_name:"",
price: ,
description:"",
image:"",
category_id: 2,

product_name:"",
price: ,
description:"",
image:"",
category_id: 2,

product_name:"",
price: ,
description:"",
image:"",
category_id: 2,